[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "TEAM2556-2025-REEFScape"
version = "0.1.0"
description = "FRC Robot Project using Python, PyRobot, and WPILib"
authors = [
    { name="Team2556", email="team@example.com" }
]
dependencies = [
    # "wpilib", #really need?
    # "robotpy"
]

[tool.pytest.ini_options]
testpaths = ["tests"]


[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2024.3.2.2"

# Which extra RobotPy components should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = [
    "all"
    # "apriltag"
    # "commands2"
    # "cscore"
    # "navx"
    # "pathplannerlib"
    # "phoenix5"
    # "phoenix6"
    # "playingwithfusion"
    # "rev"
    # "romi"
    # "sim"
]

# Other pip packages to install
requires = [
    'numpy',
    'scipy'
    # 'pynetworktables',
    # 'pyfrc',
    # 'robotpy-hal-sim',
    # 'robotpy-wpilib',
    # 'robotpy-wpiutil',
    # 'robotpy-ctre',
    # 'robotpy-rev',
    
    # 'xarray',

]